### ISSUE TITLE
Tool tips not going away on mobile

### ISSUE THREAD

**Issue by human37** [russell-hustle/lyrical#11]
We need to check if the user is on mobile and then remove the tool tips. Because randomly if you click the leaderboard or more info the tooltip gets displayed over the content and won't go away until you tap somewhere else.

**Comment by human37** [comment]
I noticed this issued on safari for iOS

**Comment by evad1n** [comment]
iOS is cringe

**Comment by evad1n** [comment]
For real tho I don't have safari
Quick google might help: [first result](https://stackoverflow.com/questions/63289645/is-there-a-way-to-force-a-vuetify-tooltip-to-close-safari-browser-on-the-click)
I don't think it's too complex so you should do it as you can actually test it on safari

**Comment by evad1n** [comment]
this is what I would try:
https://stackoverflow.com/questions/53769291/using-vuetify-tooltip-v-tooltip-component-with-an-external-activator-i-e-not
The comment about binding v-hover to v-model

**Comment by human37** [comment]
Thanks when I get some more time today I  will look into this, Have you tried testing on chrome mobile to see if you get similar issues? I can download it also right now.

**Comment by evad1n** [comment]
Im pretty sure it is just safari cuz apple. I havent noticed anything

**Comment by human37** [comment]
Yeah you're probably right, I'll put in a PR today for it

**Comment by human37** [comment]
[![image](https://user-images.githubusercontent.com/48261561/104151470-59b47600-539a-11eb-8e98-54be5daa1939.jpeg)]()

**Comment by evad1n** [comment]
IOS tooltip workaround
