### ISSUE TITLE
Data persistence

### ISSUE THREAD

**Issue by human37** [russell-hustle/lyrical#5]
My database likes to delete itself every day, looked it up and it's a thing with Heroku it needs to re initialize the file system daily and that ends up clearing the database, so I must change it to use Postgres or some other system for data storage

**Comment by evad1n** [comment]
# kinda *cringe*

**Comment by human37** [comment]
It doesn't delete itself anymore, but noticed weird issues with the leaderboard not updating? like its cached or something. Using a get request through postman it always was current, but Vue is not updating it every time the leaderboard icon is clicked.

**Comment by evad1n** [comment]
i looked at it and it might be because vue doesnt watch deep changes (object data) by default. it looks like an array though so not sure. try calling this.$forceUpdate() after and see if that fixes it. If not then it is not a problem with vue.

**Comment by human37** [comment]
Alrighty I'll try looking into that, thanks man

**Comment by human37** [comment]
Pretty sure it was because I never closed the database connection, it seems to be working great now
